### ISSUE TITLE
Add nav reviewer for changes to mkdocs.yml

### ISSUE THREAD

**Issue by ContentBrewmaster** [CivicActions/handbook#1018]
Any PRs that would change the guidebook navigation must be reviewed by a content designer. For the initial period, @ContentBrewmaster will review the PRs.

**Comment by ContentBrewmaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add reviewer for changes to navigation](https://trello.com/c/1fhES1At/336-add-reviewer-for-changes-to-navigation)

**Comment by dmundra** [comment]
@ContentBrewmaster Owen added you to https://github.com/orgs/CivicActions/teams/docs and we will set it up so the mkdocs.yml file requires approval from that team.
