### ISSUE TITLE
Add instructions to configure git commit signing to the guidebook

### ISSUE THREAD

**Issue by dmundra** [CivicActions/handbook#1051]
Potential location is https://guidebook.civicactions.com/en/latest/common-practices-tools/security/encryption/

**Comment by sfmcgee** [comment]
I think this may be a better location, on the git page: https://guidebook.civicactions.com/en/latest/practice-areas/engineering/git/

**Comment by dmundra** [comment]
Sounds good @sfmcgee!

**Comment by sfmcgee** [comment]
Question for you @dmundra - for example commands and screenshots, is it ok to use my name/username, like I did in the GNET version of the instructions? I'll definitely want to remove my email address from the example, though.

**Comment by dmundra** [comment]
Ya I think so, you can also (if you want to) replace it will placeholders like an emphasized username and email address example. Like _username_ and _username@example.org_.
