### ISSUE TITLE
Added underline text decoration for links in the content

### ISSUE THREAD

**Issue by dmundra** [CivicActions/handbook#1088]
Request from @mgifford

**Comment by mgifford** [comment]
Yes, this isn't a best practice:

![Screenshot from our guidebook](https://user-images.githubusercontent.com/116832/228014683-cd545dcd-9869-4cb3-a2a6-1346edba76c0.png)

  
  
While this is:

![Screenshot from a GDS page](https://user-images.githubusercontent.com/116832/228014712-43087b4e-0dba-4567-a8a1-45ee8e619a1e.png)

https://design-system.service.gov.uk/get-started/focus-states/

Maybe we don't need to do as excellent a job as the GDS. Here are some ideas I proposed on Drupal.org about links [https://www.drupal.org/project/bartik/issues/1993574](https://www.drupal.org/project/bartik/issues/1993574)

Also see:

- https://www.tempertemper.net/blog/why-you-should-almost-always-underline-your-links
- https://medium.com/vassar-design/links-with-underlines-as-a-best-practice-fe1ba0d6ba71

**Comment by mgifford** [comment]
This is much, much better: `a { color: inherit }` than what we have now, which is `{ color: inherit; text-decoration: none; }`

@dmundra is this just a matter of adding it here https://github.com/CivicActions/guidebook/blob/master/assets/css/extra.css and overriding what is in main.css?

**Comment by dmundra** [comment]
Yup @mgifford that is the approach.
