### ISSUE TITLE
Purpose of the asterisk at the end of each of the holiday dates

### ISSUE THREAD

**Issue by kaise-lafrai** [CivicActions/handbook#1353]
https://github.com/CivicActions/guidebook/blob/ea0dc4339bfe2fff8193e396f65cf0b6206ba673/employee-benefits/README.md?plain=1#L15

Looking at the holiday schedule, I noticed an asterisk at the end of each of the dates. I tried looking for some details around the page that is in reference to those asterisks. Couldn't find anything. Maybe we should remove them?

See below for those asterisks. 

```
| Holiday                             | Dates                         |
| ----------------------------------- | ----------------------------- |
| New Year's Day                      | January 1st\*                 |
| Birthday of Martin Luther King, Jr. | Third Monday in January       |
| Memorial Day                        | Last Monday in May            |
| Juneteenth                          | June 19th\*                   |
| Independence Day                    | July 4th\*                    |
| Labor Day                           | First Monday in September     |
| Veterans Day                        | November 11th\*               |
| Thanksgiving Day                    | Fourth Thursday in November   |
| Day after Thanksgiving              | The Friday after Thanksgiving |
| Christmas Day                       | December 25th\*               |

```

**Comment by dmundra** [comment]
Good catch. Looks like the asterisk got dropped from this text which is the reason for it:

> If a holiday falls on a the weekend, the US office observes on the preceding Friday for Saturday holidays and the following Monday for Sunday holidays.

Would you be open to making the edit to put that asterisk back?

**Comment by kaise-lafrai** [comment]
Once build is complete, this is ready for review.

**Comment by kaise-lafrai** [comment]
I also noticed an extra word in the sentence. Removed it so it is more grammatically correct.

> If a holiday falls on **a the** weekend, the US office observes on the preceding Friday for Saturday holidays and the following Monday for Sunday holidays.
> 
> to 
> 
> If a holiday falls on a weekend, the US office observes on the preceding Friday for Saturday holidays and the following Monday for Sunday holidays.
