### ISSUE TITLE
Set up common Video Call Best Practices section

### ISSUE THREAD

**Issue by mgifford** [CivicActions/handbook#746]
The **Video Call Best Practices** should be its own section in and not be within [Google Meet (formerly Google Hangouts)](https://handbook.civicactions.com/en/latest/050-how-we-work/tools/google-hangouts/#google-meet-v-zoom)

Some of this is specific to Google, but in general we'd like to highlight how to do a good video call. 

## Video Call Best Practices

- Be on time - please! Every 10 seconds actually matters
- Default to video on for all video meetings
- Add a photo to your account so it shows up in Google Meet if your camera is off
- We use the chat and screen sharing features
- Turn off your camera or reduce bandwidth if connection is poor
- Use some kind of headset or headphones instead of relying solely on computer mic (computer mics can sometimes create echoes)
- Use proper etiquette for video call professionalism (consider the appropriateness of background visuals/noise, attire/dress, use of effects, eating, muting, etc.)
- It's okay to mute others or ask them to mute themselves
- We can invite people outside of CivicActions
- If someone hears an echo & you don't, then it's likely your computer creating the echo. Try using headphones or plugging them in again
- Use screen sharing for demos and for pairing

**Comment by dmundra** [comment]
Should it go in here https://handbook.civicactions.com/en/latest/050-how-we-work/virtual-workplace-basics/ or its own page?

**Comment by mgifford** [comment]
I think if it is right under best practices it will be read more https://handbook.civicactions.com/en/latest/050-how-we-work/virtual-workplace-basics/#communication-best-practices

That said, really depends on the page length. I'd start with this page and if we hear it is too long we can break it out.

**Comment by dmundra** [comment]
@mgifford following this https://www.bbc.com/worklife/article/20220621-the-case-for-turning-off-your-zoom-camera we should keep the following note about video on and maybe add to it:

> Teams are encouraged to turn on their video during calls. This helps most people build trust and deeper connections. If you feel being on camera is draining or stressful, it is recommended that you turn on your video at the beginning of the call and tell the other participants that you can focus better without the video. You can also let your team members know about this preference ahead of time if you would rather not discuss it during the call.

Thoughts?

**Comment by cheapwebmonkey** [comment]
@dmundra @mgifford suggesting something that does not lead with what works best for neurotypical folks but is the most inclusive. The issue with phrasing as the BBC does is that the phrasing is still othering neurodivergent folks. 

It is not a preference or "more comfortable" for folks who are neurodivergent.

**Comment by cheapwebmonkey** [comment]
suggesting something like,  "We wish to host the most inclusive and welcoming spaces for all. Therefore, please use the camera option that works best for you. 

While we acknowledge that "cameras on" may work best for some people, we recognize that it does not work for everyone, which is ok."

**Comment by cheapwebmonkey** [comment]
I would also suggest that folks add their pronouns to their name in the virtual meeting as not all calls have an intro section.

**Comment by grugnog** [comment]
Note that Zoom has [pronouns built-in to the profile/clients](https://support.zoom.us/hc/en-us/articles/4402698027533-Adding-and-sharing-your-pronouns) and has controls for you to determine if you share your pronouns on every meeting or if you want to decide each time. These can be configured on https://zoom.us/profile

I think it would be helpful to include something to the effect that: "don't assume that someone is less interested if their camera is off but be aware that it may be a way of staying focused"

I also think having something around the context/purpose of the call would be helpful - the benefits of video are a lot higher for that 5 minute conversation to untangle an emotionally involved miscommunication than for a 4 hour long debug screen-share.

I think that for folks having Zoom fatigue it's also worth looking at how to reduce the number/duration of meetings and calls. If someone isn't either delivering or getting value from a call (that they couldn't get from reading the meeting notes) we should have clear expectations/space for them to let the host/inviter know this and potentially skip the meeting in future.

**Comment by cheapwebmonkey** [comment]
Thank you for pointing out the Zoom pronoun settings, @grugnog. I was unaware that they had been added. Perhaps we can link to this info?

"don't assume that someone is less interested if their camera is off but be aware that it may be a way of staying focused" 
is awesome

Would be helpful to add agendas to meeting invites in order to help convey context?

**Comment by dmundra** [comment]
Started a google doc to capture the thoughts for this handbook page: https://docs.google.com/document/d/1KBtrlVMB9JHWCU-VdQD9EmzJat5RtRZezy45yo4hCFY/edit?usp=sharing

Please feel free to add comments and make edits to it.

**Comment by dmundra** [comment]
Thanks @cheapwebmonkey and @TheETupper for your updates.

@mgifford I think separate page under '050-how-we-work'. Would love to get your and @grugnog input on the doc as well before shipping it.
