### ISSUE TITLE
Needs updating: "How and when to contribute to the handbook"

### ISSUE THREAD

**Issue by alanna-blinn** [CivicActions/handbook#751]
All the information about Trello seems to be outdated. The Trello board doesn't exist. Also not sure if there's a documentation working group.

**Comment by dmundra** [comment]
@alanna-casey looks like the [trello board](https://trello.com/b/ZKx6l4bC/documentation-working-group) is back (I can see it) and ya I forgot it existed. Also recently [thread is slack](https://civicactions.slack.com/archives/C02G3EY55/p1650558949696359?thread_ts=1650556727.762779&cid=C02G3EY55) asking this same question so maybe time for an update?

**Comment by alanna-blinn** [comment]
Thanks for following up on this, @dmundra, and for picking up the issue. I can see the board now too and joined. Also following the channel more closely too to see where I can be helpful.
