### ISSUE TITLE
Broken link on Zoom page

### ISSUE THREAD

**Issue by brdunfield** [CivicActions/handbook#830]
https://handbook.civicactions.com/en/latest/050-how-we-work/tools/zoom/

There is a link on this page:
> download the [Zoom browser extensions](https://handbook.civicactions.com/en/latest/en/latest/050-how-we-work/tools/browserextensions/#browser-extensions)

Which leads to a 404. I would try to put in a fix myself but I am not sure where it is meant to point to.

**Comment by dmundra** [comment]
Thanks @brdunfield. I believe it should go here https://handbook.civicactions.com/en/latest/050-how-we-work/tools/browserextensions/#browser-extensions

Please submit a fix when you get a chance. Thank you!
