### ISSUE TITLE
Update Referral policy page

### ISSUE THREAD

**Issue by jcklpe** [CivicActions/handbook#855]
I'd be willing to make a pull request myself but I'm so new and I don't really know what the policy on this is.   
  
This page is about how to send an employee referral and the policy surrounding that etc: [https://handbook.civicactions.com/en/latest/030-policies/employee-referral-bonus/](https://handbook.civicactions.com/en/latest/030-policies/employee-referral-bonus/)  
  
We now have greenhouse though so I think we could update it to include guidance on using the greenhouse referral links. Those make things waaaay easier.

**Comment by dmundra** [comment]
Hey @jcklpe please submit a pull request with the additions. We would love to have it and I believe it will automatically involve legal for review.

**Comment by jcklpe** [comment]
Done!

**Comment by jcklpe** [comment]
#856
