### ISSUE TITLE
Broken link: Backend Development > Drupal-specific Coding Standards

### ISSUE THREAD

**Issue by ContentBrewmaster** [CivicActions/handbook#902]
Link "[The Most Important Decision In Developing A Drupal Site: Contributed Vs. Custom Development](https://civicactions.com/blog/developing-drupal-site-contributed-vs-custom-development/)" results in 404. Guessing we took this blog post off our Medium page.

**Comment by dmundra** [comment]
Looks like we used to have a blog (wayback machine captured a live instance of it from 2015 https://web.archive.org/web/20150502060739/http://www.civicactions.com/blog) but that blog page itself did not get captured. I cannot find a copy in google drive, maybe someone as an email for it to resurrect it. If not then based to remove this link from that page.

**Comment by dmundra** [comment]
@grugnog do you happen to have a record of that blog post?

**Comment by dmundra** [comment]
@openprivacy led me to find the archive.org link for this one https://web.archive.org/web/20140325022556/http://www.civicactions.com/blog/most_important_decision_developing_site_Contributed_vs_custom_development
