### ISSUE TITLE
Style Guide Update

### ISSUE THREAD

**Issue by sharjeelaziz** [CivicActions/handbook#908]
In our handbook, we are using a mix of title case and sentence case capitalization. What is the preferred way and can we update the style guide?

**Comment by dmundra** [comment]
@mgifford I feel that we did discussed this in slack at some point?

**Comment by mgifford** [comment]
Looking through Slack the trend is consistently, "Move to sentence case"

Might be something to add to https://civicactions-style-guide.readthedocs.io/

**Comment by sharjeelaziz** [comment]
Maybe we can start by updating https://handbook.civicactions.com/en/latest/000-contributing/writing-style-guide/
