### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by ContentBrewmaster** [CivicActions/handbook#916]
A search for “tech stipend” returns duplicate results for 4 pages. This happens for some but not all pages in the handbook when searching for content.

We need to investigate this bug or setting that could be tweaked to return only 1 result.

**Comment by dmundra** [comment]
Link for reference https://handbook.civicactions.com/en/latest/search.html?q=tech+stipend

@ContentBrewmaster digging into the code and search feature, I feel that the search results are working as the original author intended. The search feature indexes both the entire page and also the each page's section headers separately causing the duplicate cases here. I don't see any options to adjust that.

One option could be replacing the search with google search, something like you would get if you type `site:handbook.civicactions.com tech stipend` in google.

My recommendation would be to possible consider replacing the search with google search. One advantage of that would be we could have a google search and includes all CA sites and note just the handbook (e.g. if you type `site:civicactions.com accessibility` in google you get results from our a11y site, home site, and the handbook).

Thoughts?

**Comment by dmundra** [comment]
The material theme (draft #926, https://handbook.civicactions.com/en/material/) would solve this duplicate search issue.

**Comment by ContentBrewmaster** [comment]
We will be moving to a new theme so the issue can be resolve.
