### ISSUE TITLE
Fix link to harassment policy on Culture page

### ISSUE THREAD

**Issue by ContentBrewmaster** [CivicActions/handbook#919]
On the [Culture page](https://handbook.civicactions.com/en/latest/020-about-us/culture/), there's a 404 error for the link "[Policy Against Proscribed Harassment and Discrimination](https://handbook.civicactions.com/en/latest/030-policies/anti-harassment-policies/) near the bottom of the page.

Acceptance Criteria
- Link to the harassment policy is **https://handbook.civicactions.com/en/latest/040-employee-handbook-us/anti-harassment-policies/#policy-against-proscribed-harassment-and-discrimination**

**Comment by dmundra** [comment]
@ContentBrewmaster do you want to take a stab at updating it? I can guide you through the editing if you like.

**Comment by ContentBrewmaster** [comment]
I did in #920 but can't get the 2nd link to work correctly (it needs to go to a specific heading).

**Comment by dmundra** [comment]
@ContentBrewmaster I am not seeing the link change when I view the files in 920, https://github.com/CivicActions/handbook/pull/920/files. Also I noticed the links are absolute. Try relative links and you can use `#...` to specify the specific header.

I think the first link would be:

```
[Policy Against Proscribed Harassment and Discrimination](../040-employee-handbook-us/anti-harassment-policies.md)
```

then then the second link would be

```
[reporting procedures](../040-employee-handbook-us/anti-harassment-policies.md/#policy-against-proscribed-harassment-and-discrimination)
```

Those should work when you preview the changes in GitHub.

**Comment by ContentBrewmaster** [comment]
Links fixed. Thank you @dmundra!
