### ISSUE TITLE
Add documentation/instructions on updating navigation for editors

### ISSUE THREAD

**Issue by dmundra** [CivicActions/handbook#980]
We need a helpful guide to let editors know how to update the site navigation https://github.com/CivicActions/handbook/blob/master/.config/mkdocs.yml#L36 including adding new items, removing old ones (when deleting a page), and handling child menu items.

Links:
- https://www.mkdocs.org/user-guide/configuration/#nav
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

**Comment by ContentBrewmaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add documentation/instructions on updating navigation for editors](https://trello.com/c/fhfdGxdm/281-add-documentation-instructions-on-updating-navigation-for-editors)

**Comment by ContentBrewmaster** [comment]
Drafting content for updating site navigation as part of larger rewrite of **About this guidebook** section.

**Comment by ContentBrewmaster** [comment]
Draft ready for review by @grugnog 
https://docs.google.com/document/d/10swx2y3Xn6TO_hONRngr8QlnOOWYokVSfq5mG9XN8mg/edit#heading=h.t2p3uctxe5mu

**Comment by dmundra** [comment]
@ContentBrewmaster and @grugnog once we get the new documentation into the guidebook I think we should do a v2.1 release and note all the content changes, redirects, new documentation, and other items? You can see the changes since v2.0 here https://github.com/CivicActions/guidebook/compare/v2.0...master

What do you both think?

**Comment by ContentBrewmaster** [comment]
Content in review with Kelly Smith.

**Comment by ContentBrewmaster** [comment]
#1035 has been merged with new instructions on updating navigation.
