### ISSUE TITLE
Wave a11y report errors for material theme

### ISSUE THREAD

**Issue by dmundra** [CivicActions/handbook#981]
Wave is reporting a lot of errors for the material theme (currently 34 errors https://wave.webaim.org/report#/https://handbook.civicactions.com/en/latest/ and 8 contrast errors when using the browser tool).

**To dos**

- [x] Fix contrast errors in the "read the docs" popup that allows switching of branches.

Follow-up on the Wave a11y errors (see quote below from #926)

> Looks like the a11y issues are known:
> * https://github.com/squidfunk/mkdocs-material/issues/4006
> * https://github.com/squidfunk/mkdocs-material/discussions/3156
> 
> For the keyboard navigation for sub-topics one option is enabling navigation sections and navigation expansion (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections). We can also introduce tabs, if we overhaul the menu. Right now all top level pages would be tabs and that is a lot of tabs.

**Comment by ContentBrewmaster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix accessibility issues with new theme](https://trello.com/c/yH4BXYsy/280-fix-accessibility-issues-with-new-theme)

**Comment by dmundra** [comment]
Fix for contrast errors in #1004 and also the keyboard navigation for collapsed menu items is fixed the latest version (9.0.3).

**Comment by dmundra** [comment]
I believe the author will be fixing accessibility errors so as long as we keep our version up to date then we should get those fixes. I don't think wave errors will go down to 0 based on the architecture of the theme so for now closing this issue.
